default: &default
  adapter: redis
  url: <%= RedisConfig.new.url %>

development:
  <<: *default
  channel_prefix: cableready_test_development

test:
  adapter: test

production:
  <<: *default
  channel_prefix: cableready_test_production
